import {getPlayer,currentWeek} from '@/lib/players';
import {getEspnGames,matchupFor,getCombinedNews} from '@/lib/espn';
import {playerMetrics} from '@/lib/fantasy';
import {notFound} from 'next/navigation';
import PlayerAvatar from '@/components/PlayerAvatar';
export default async function Page({params}:{params:{id:string}}){
 const p=await getPlayer(params.id); if(!p)notFound();
 const [games,news,ppr,half,standard]=await Promise.all([getEspnGames(),getCombinedNews(14),playerMetrics('ppr'),playerMetrics('half'),playerMetrics('standard')]);
 const matchup=matchupFor(p.team,games); const pm=ppr.find(x=>x.player.id===p.id),hm=half.find(x=>x.player.id===p.id),sm=standard.find(x=>x.player.id===p.id);
 const last=(p.lastName||p.name.split(' ').slice(-1)[0]).toLowerCase(); const related=news.filter(n=>`${n.title} ${n.description}`.toLowerCase().includes(last)).slice(0,4);
 return <section className="wrap section"><div className="profileHero"><PlayerAvatar p={p} className="profileShot"/><div><div className="eyebrow">{p.team} • {p.position}</div><h1>{p.name}</h1><p className="muted">Week {currentWeek()}{p.injuryStatus?` • ${p.injuryStatus}`:' • No injury designation'}</p><div className="actions">{p.espnId&&<a className="tag" target="_blank" rel="noreferrer" href={`https://www.espn.com/nfl/player/_/id/${p.espnId}`}>ESPN ↗</a>}<a className="tag" target="_blank" rel="noreferrer" href="https://sports.yahoo.com/nfl/">Yahoo Sports ↗</a></div></div><div className="playerProjection"><small>WEEK {currentWeek()} PPR PROJECTION</small><b>{pm?.projection.toFixed(1)??'—'}</b><span>{pm?.source||'Projection feed'}</span></div></div><div className="playerDashboard"><div className="card"><div className="eyebrow">THIS WEEK</div><h2>{matchup?`${matchup.home?'vs':'@'} ${matchup.opponent}`:'Matchup unavailable'}</h2><p className="muted">{matchup?`${new Date(matchup.date).toLocaleString()} • ${matchup.status}`:'Schedule will update automatically.'}</p>{pm?.matchupRank&&<div className={`matchupBadge matchup-${pm.matchupTone||'neutral'}`}>MATCHUP #{pm.matchupRank} vs {p.position} • {pm.matchupLabel}</div>}<div className="miniMetrics"><span><small>PPR</small><b>{pm?.projection.toFixed(1)??'—'}</b></span><span><small>HALF</small><b>{hm?.projection.toFixed(1)??'—'}</b></span><span><small>STD</small><b>{sm?.projection.toFixed(1)??'—'}</b></span></div></div><div className="card"><div className="eyebrow">2026 FANTASY PRODUCTION</div><h2>{pm?.seasonPoints.toFixed(1)??'—'} PPR pts</h2><div className="miniMetrics"><span><small>OVERALL</small><b>{pm?.rank?`#${pm.rank}`:'—'}</b></span><span><small>{p.position} RANK</small><b>{pm?.positionRank?`#${pm.positionRank}`:'—'}</b></span><span><small>VALUE</small><b>{pm?.value.toFixed(1)??'—'}</b></span></div><p className="muted">Fantasy scoring data refreshes automatically; source availability can vary by player.</p></div></div><div className="sectionHead playerNewsHead"><div><div className="eyebrow">ESPN + YAHOO SPORTS</div><h2>Latest {p.lastName||p.name} News</h2></div></div><div className="newsGrid">{related.length?related.map(n=><a className="newsCard" href={n.link} target="_blank" rel="noreferrer" key={n.link}><span className="tag">{n.source}</span><h3>{n.title}</h3><p>{n.description.slice(0,180)}</p></a>):<div className="card muted">No recent matching headline right now.</div>}</div></section>
}
