const experts=['Cyrus','Aiden','Gerardo','Nehemiah'];
const tools=[['⚔️','Start / Sit','Compare players and see Chubb Club, expert and community opinions.','/start-sit'],['🔄','Trade Analyzer','Evaluate trades using roster needs, rankings and rest-of-season value.','/trades'],['🚨','Waiver Wire','Find adds, drops, stashes and weekly breakout candidates.','#'],['🏈','NFL Players','Search live fantasy-relevant NFL players and profiles.','/players']];
export default function Home(){return <main><section className="hero"><div><span className="eyebrow">FANTASY FOOTBALL • BUILT FOR YOUR LEAGUE</span><h1>Make better fantasy decisions.</h1><p>Rankings, lineup help, trades, waivers, real expert advice and a community built around your actual fantasy leagues.</p><div className="actions"><button>Join Chubb Club</button><button className="ghost">View Rankings</button></div><div className="mini"><span>✓ Weekly rankings</span><span>✓ Expert advice</span><span>✓ League communities</span></div></div><img className="heroLogo" src="/chubb-club-logo.png"/></section>
<section id="tools"><div className="sectionTitle"><span>DECISION CENTER</span><h2>What are you trying to decide?</h2></div><div className="grid">{tools.map(x=><article key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p><a href={x[3]}>Open tool →</a></article>)}</div></section>
<section id="rankings" className="panel"><div><span className="eyebrow">CHUBB CLUB RANKINGS</span><h2>Four opinions. One consensus.</h2><p>Each Chubb Club expert gets weekly, overall and rest-of-season rankings. Compare every expert or use the combined Chubb Club Consensus.</p><div className="chips">{experts.map(e=><span key={e}>{e}</span>)}<span>Chubb Club Consensus</span></div></div><div className="rankcard"><b>WEEKLY RANKINGS</b>{['WR1  Player A','WR2  Player B','WR3  Player C','WR4  Player D'].map((x,i)=><div className="rank" key={x}><span>{x}</span><small>{i%2?'—':'▲ '+(i+2)}</small></div>)}</div></section>
<section id="community"><div className="sectionTitle"><span>YOUR LEAGUES. YOUR PEOPLE.</span><h2>Fantasy football should be social.</h2><p>Add friends, create or import leagues, post trades, vote on start/sits, talk trash and share Chubb Club tools directly to your league feed.</p></div><div className="feed"><div className="post"><b>@Cyrus</b><small> • The Boys League</small><p>Who wins this trade?</p><div className="trade"><span>Player A + Player B</span><strong>⇄</strong><span>Player C</span></div><div className="muted">👍 42 &nbsp; 💬 18 &nbsp; 📊 Vote</div></div><aside><h3>League Hub</h3><p>🏆 Standings</p><p>💬 League Chat</p><p>🔄 Recent Trades</p><p>📊 Polls</p><p>🔥 Weekly Matchups</p></aside></div></section>
<section id="experts" className="dark"><div className="sectionTitle"><span>CHUBB CLUB EXPERTS</span><h2>Get advice from a real person.</h2><p>Paid members can send roster-aware trade, waiver and lineup questions directly to Chubb Club experts.</p></div><div className="experts">{experts.map((e,i)=><div key={e}><div className="avatar">{e[0]}</div><h3>{e}</h3><small>CHUBB CLUB EXPERT</small><p>{['Trades • WRs','Waivers • RBs','Rankings • Trades','Start/Sit • Sleepers'][i]}</p><button className="ghost">View Profile</button></div>)}</div></section>
<section className="pricing"><div><span className="eyebrow">MEMBERSHIP</span><h2>Start free. Upgrade when you want more.</h2></div><div className="plans"><article><h3>Free</h3><b>$0</b><p>Community, basic rankings and limited decision tools.</p></article><article className="featured"><span>POPULAR</span><h3>Chubb Club+</h3><b>$5.99<small>/mo</small></b><p>Full rankings, unlimited tools and personal expert questions.</p></article><article><h3>Chubb Club Pro</h3><b>$9.99<small>/mo</small></b><p>Everything in Plus with more expert access and priority features.</p></article></div></section>
</main>}
